- defaults:
    link:
        create: true
        relink: true
        force: true

- clean: ['~/.config']

- link:
    ~/.configs/iterm2/com.googlecode.iterm2.plist: .apps/iterm2/com.googlecode.iterm2.plist
- shell:
    - [defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.configs/iterm2", Setting up preference folder]
    - [defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true, Use custom preference folder]

